In [1]:
l1 = [20,30,40]
l2 =[50,60,70]
print (l1+l2)

[20, 30, 40, 50, 60, 70]


In [6]:
import numpy as np
a = np.array([40,50,60])
print (a)

[40 50 60]


In [4]:
l1 =[[20,30],[40,50,60]]
print (l1)

[[20, 30], [40, 50, 60]]


In [7]:
import numpy as np 

a = np.array([20,30,40])
b = np.array([60,70,80])
print(a)
print (a+b)
print (a*b)

[20 30 40]
[ 80 100 120]
[1200 2100 3200]


In [8]:
import numpy as np

arr=np.array([[10,20,30,40],[50,60,70,80]])
print (arr[0:2,0:2])
print(arr[0:2,0:3])
print (arr[0,1:3])
print (arr[1,2:4])

[[10 20]
 [50 60]]
[[10 20 30]
 [50 60 70]]
[20 30]
[70 80]


In [9]:
import numpy as np

arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print (arr[2,2])


60


In [10]:
import numpy as np

arr=np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])

print (np.shape(arr)) 
print (np.size(arr))
print (np.ndim(arr))
print (arr.dtype) 
print (len(arr)) 
print (np.size(arr))
print(type(arr))
print (arr.astype(float))
print (arr.astype(str))

(3, 4)
12
2
int64
3
12
<class 'numpy.ndarray'>
[[10. 20. 30. 40.]
 [50. 60. 70. 80.]
 [20. 40. 60. 80.]]
[['10' '20' '30' '40']
 ['50' '60' '70' '80']
 ['20' '40' '60' '80']]


In [11]:
import numpy as np

a = [[10,20,30,40],[50,60,70,80],[20,40,60,80]]
arr = np.array(a)

print (arr)
print (arr.shape) #rows,coumns
print (len(arr))  #number of nested values
print (np.size(arr))  #number of elements
print (type(arr))  #datatype of variable
print (arr.dtype)  #datatype of array
print (arr.astype(int))#conversion of data

[[10 20 30 40]
 [50 60 70 80]
 [20 40 60 80]]
(3, 4)
3
12
<class 'numpy.ndarray'>
int64
[[10 20 30 40]
 [50 60 70 80]
 [20 40 60 80]]


In [12]:
#Mathematical Operation

import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print (arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [13]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print (arr1-arr2)
print (np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [14]:
import numpy as np

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print (arr1*arr2)
print (np.multiply(arr1,arr2))
print (arr1/arr2)
print (np.divide(arr1,arr2))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]
[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [15]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print (np.power(arr1,arr2))

[ 9 16  4  1]


In [ ]:
arr1 = np.array([ 9,16,4,1])
print (np.sqrt(arr1))

In [16]:
#Join and split

a = [30,40,50]
b = [5,5,3]
print (a+b)

[30, 40, 50, 5, 5, 3]


In [17]:
#Concatenate

import numpy as np

arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print (np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [18]:
print (np.concatenate([arr1,arr2],axis =0))

[30 40 50  5  5  3]


In [20]:
import numpy as np

arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])


In [21]:
print (np.concatenate([arr1,arr2],axis =0))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [22]:
print (np.concatenate([arr1,arr2],axis =1))

[[30 40  5  5]
 [50 10  3  3]]


In [23]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [24]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [4]:
import numpy as np
a = np.array([20,40,30,40,10,20])
print(np.array_split(a,3))

[array([20, 40]), array([30, 40]), array([10, 20])]


In [5]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,3)
print (b[1])

[30 40]


In [8]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,2)
print (b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]


In [9]:
#Adding and Remo

import numpy as np

a = np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [11]:
import numpy as np

a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [19]:
import numpy as np

a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [20]:
print(np.insert(a,1,50)) #array,index,value
print(np.insert(a,1,[50,60], axis = 1))

[20 50 40 60 80]
[[20 50 40]
 [60 60 80]]


In [22]:
print(a)
print (np.delete(a,1))

[[20 40]
 [60 80]]
[20 60 80]


In [25]:
print(a)
print()
print (np.delete(a,1, axis = 0))
print()
print (np.delete(a,1, axis = 1))

[[20 40]
 [60 80]]

[[20 40]]

[[20]
 [60]]


In [26]:
#Sort,Filter and Search

import numpy as np

ar = np.array([7,8,4,12,9])
print (np.sort(ar))

[ 4  7  8  9 12]


In [28]:
ar = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print (np.sort(ar))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [33]:
#Search
ar = np.array([3,4,1,7,8])
s = np.where(ar % 2 == 0)
print (s)

(array([1, 4]),)


In [34]:
#Search
ar = np.array([1,2,3,4,5])
ss = np.searchsorted(ar,2 )
print (ss)

1


In [36]:
#Filter

import numpy as np
ar = np.array ([20,30,40,50])

fa =[True,False,True,False]
new = ar[fa]
print(new)

[20 40]


In [37]:
import numpy as np
ar = np.array ([20,30,40,50])

fa =[True,False,False,False]
new = ar[fa]
print(new)

[20]


In [1]:
import numpy as np
ar = np.array ([20,30,40,50])

fa = ar>35

new = ar[fa]
print(new)

[40 50]


In [3]:
import numpy as np
ar = np.array ([2,3,4,5])

fa = ar%2==1

new = ar[fa]
print(new)

[3 5]


In [8]:
#Aggregating Functions
import numpy as np 
a = np.array([20,40,60,70])
print (np.sum(a))
print (np.min(a))
print (np.max(a))
print (np.size(a))
print (np.mean(a))
print (np.cumsum(a))
print (np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [19]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print (price,"\n",quantity)

print(np.cumsum([price,quantity]))
print()
print(np.cumprod([price,quantity], axis =0))
print()
c = np.cumprod([price,quantity], axis =0)
print (c[1])
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
[ 100  250  449  649  899 1029 1039 1089 1119 1159 1189 1199]

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]

[1000 7500 5970 8000 7500 1300]
31270


In [7]:
#Statistical Fuinctions

import numpy as np
import statistics as stats
baked_food = [200,300,150,130,200,280,170,188]

a =np.array(baked_food)
print(np.mean(baked_food)) #sum of all the values/number of values
print(np.median(baked_food)) #central value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

202.25
194.0
200
55.68157235567257
3100.4375


In [8]:
# -1 represents inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship

tobacco_consumption =[30,50,10,30,50,40]
deaths =[100,120,70,100,120,112]

print (np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [9]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]

print (np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
